### ISSUE TITLE
Replace rustc-serialise by Serde

### ISSUE THREAD

**Issue by Kerollmops** [koivunej/eventstore-tcp#1]
...even if this is a `dev-dependency`, `rustc-serialise` has become deprecated.

**Comment by koivunej** [comment]
Good point! I think [`hex`](https://github.com/KokaKiwi/rust-hex) might be more appropriate as it only includes the `FromHex` support used in codec tests. Not sure if serde provides the hex functionality.

**Comment by koivunej** [comment]
I actually already had another (uncommited) `examples/decoder` which I have been using and accidentially used `hex` crate for implementing it. Committing this soon.
