### ISSUE TITLE
Volatile subscriptions

### ISSUE THREAD

**Issue by Kerollmops** [koivunej/eventstore-tcp#12]
- refactoring to use `tokio_proto::streaming::multiplex` instead of `tokio_proto::multiplex`
- current messages are ok as headers, but appeared events could probably be body chunks
- maintaining a subscription by pumping events to a `futures::sink::Sink`, detecting overflows and dropping the subscription

**Comment by koivunej** [comment]
There is already #9. In general, I am not sure if all these issues are needed since there is the README file. 

I can try to create smaller tasks in a more "help wanted" fashion.
