### ISSUE TITLE
CustomTryFrom/Into should be replaced by TryFrom/Into

### ISSUE THREAD

**Issue by Kerollmops** [koivunej/eventstore-tcp#7]
It seems `CustomTryFrom/Into` types are a custom version of the official `TryFrom/Into` type but forcing the `try_from/into` methods to return `Self` in a tuple if an error occur.

I now that you make these Traits because you wont use the *unstable* ones. That's a really strong argument, Yep ! the **eventstore-tcp** library is in an `early-pre-alpha` version (`0.0.1`) for now, we can publish a `beta` version when all of the useful stuff is stable.

This makes the library less flexible with the standard [operators](https://doc.rust-lang.org/std/ops/trait.Carrier.html) and language inference.

As a little example, [in this snippet](https://gist.github.com/anonymous/122a5b515c1f3e469a4ba25dca2a17fa) I show you how easy it is to convert error types without using the direct closure syntax (`|_| { ... }`) and just the method you want to apply (`From::form`) instead. It seems dumb to remove the `CustomTryForm/Into` types just to use this feature but think about this little improvement for all of the recursive errors you return all around your code ? I need to know why you return `Self` according to the `Self::Error`.

As an old Rust user I can say this: "This is not Rusty!" 😄

No offense, I need to have your feedback and I will work on this library improvement (with you if you want/have time to). We need to make better experience for the developers too.

PS. I really believe that less is more, removing write-handed official-equivalent code seems to be the right way for me. And I have time to loose on this library (I ❤️ geteventstore).

**Comment by koivunej** [comment]
Firstly thanks for your PRs and sorry I might have merged them in the wrong order. Please advice on any of the issues which way would be the simplest to get the rest of them merged? I'll set up a travis-ci in the meantime.

I am definetly [for removing the CustomTryFrom/Into](https://github.com/koivunej/eventstore-tcp/pull/2#issuecomment-302607845) even though my original idea was to keep using only stable rust. I haven't used any time on this library as I've been awaiting for my tokio-proto PR to progress but I have been working on a related project which I have turned into using nightly long time ago.

> This makes the library less flexible with the standard operators and language inference.

I already started discussing the use of carrier trait here: https://github.com/koivunej/eventstore-tcp/pull/8/files#r117406120 and couldn't see any other way to also avoid cloning possibly big values.

**Comment by koivunej** [comment]
Finally done this but I can no longer understand anything except the idea of what I was trying to do. Thanks @Kerollmops for reporting and your patience way back when :) I've also updated the README with a link to the proper client by YoEight. Not sure if this is yet ready to be archived but probably soon.
